name: Groovy Script Test

on:
  workflow_dispatch:
  push:
    paths:
      - Output/RDF_Kin_Data_2022-Dec.ttl
      - shapes/*.shex
      - validate.groovy

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: groovy
          version: 1.0

  interactionData:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Generate the Shex validation reports
        run: |
          groovy validate.groovy InteractionData http://vocabularies.wikipathways.org/wp#InteractionData

  enzyme:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Generate the Shex validation reports
        run: |
          #groovy validate.groovy Enzyme http://vocabularies.wikipathways.org/wp#Protein

  interaction:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Generate the Shex validation reports
        run: |
          groovy validate.groovy Interaction http://vocabularies.wikipathways.org/wp#Interaction

  substrate:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Generate the Shex validation reports
        run: |
          #groovy validate.groovy Substrate http://vocabularies.wikipathways.org/wp#Metabolite

  measurement:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Generate the Shex validation reports
        run: |
          #groovy validate.groovy Measurement http://vocabularies.wikipathways.org/wp#???
