name: Groovy Script Test

on:
  workflow_dispatch:
  push:
    paths:
      - Output/RDF_Kin_Data_2025-July.ttl
      - shapes/*.shex
      - validate.groovy

jobs:
  ValidateCuratedRDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install groovy
        run: sudo apt install groovy

      - name: Generate the Shex validation reports - InteractionData
        run: |
          groovy validate.groovy InteractionData http://vocabularies.wikipathways.org/wp#InteractionData

      - name: Generate the Shex validation reports - Enzyme
        run: |
          groovy validate.groovy Enzyme http://vocabularies.wikipathways.org/wp#Protein

      - name: Generate the Shex validation reports - Interaction
        run: |
          groovy validate.groovy Interaction http://vocabularies.wikipathways.org/wp#Interaction

      - name: Generate the Shex validation reports - Substrate
        run: |
          groovy validate.groovy Substrate http://vocabularies.wikipathways.org/wp#Metabolite

      - name: Generate the Shex validation reports - Measurement
        run: |
          groovy validate.groovy Measurement http://vocabularies.wikipathways.org/wp#???
