name: Groovy Script Test

on:
  workflow_dispatch:
  push:
    paths:
      - Output/RDF_Kin_Data_2022-Dec.ttl
      - shapes/*.shex
      - validate.groovy

jobs:
  ValidateCuratedRDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install groovy
        run: sudo apt install groovy

      - name: Generate the Shex validation reports
        run: |
          groovy validate.groovy InteractionData http://vocabularies.wikipathways.org/wp#InteractionData
          groovy validate.groovy Enzyme http://vocabularies.wikipathways.org/wp#Protein
          groovy validate.groovy Substrate http://vocabularies.wikipathways.org/wp#???
          groovy validate.groovy Measurement http://vocabularies.wikipathways.org/wp#???
