name: Python Script Test

on:
  workflow_dispatch:
  push:
    paths:
      - KineticsData/*
      - TestData/*
      - ValidateData/*
      - createRDFKinData.py

# Sets permissions of the GITHUB_TOKEN to push results to GitHub if required
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  CreateCuratedRDF:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:        
      # step 1: checkout the repository
    - uses: actions/checkout@v4
      # step 2: define Python version to run script with
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
      # step 3: run the script in bash
    - name: run script in bash
      run: |
        ## Check if python is activated:
        which python
        ## Check version of Python
        python3 --version
        ##Update pip install
        pip install --upgrade pip
        ##Install library to read xlsx files:
        pip install openpyxl
        ls
        python createRDFKinData.py
        echo "script run successful"
       
  ValidateCuratedRDF:
    runs-on: ubuntu-latest
    needs: CreateCuratedRDF
    steps:
    # step 1: checkout the repository
    - uses: actions/checkout@v3
    # step 2: Download and run the RDF validator
    - name: Turtle Validator
      run: |
        npm install -g turtle-validator
        ttl Output/RDF_Kin_Data_2025-July.ttl
        ttl Output/RDF_Kin_Data_2025-July.ttl > validationLog2025-July.txt
        FILENAME=validationLog2025-July.txt 
        if grep -q . "${FILENAME}"; then
          echo "File is not empty"
        else
          echo "File is empty"
        fi     

